<template>
  <div class="tab-con">
    <Collapse v-model="value">
      <Panel v-for="(item,index) in tableData" :name="'1'+index" :key="index">
        {{ item.title }}
        <Row slot="content">
          <tableForm :itemData="item.itemData" :itemTitle="item.itemTitle" :itemGS="item.itemGS"></tableForm>
        </Row>
      </Panel>
    </Collapse>
  </div>
</template>
<script>
    export default {
        name: "finance",
        data(){
            return {
              value:"",
              tableData:[
                {
                  title:"偿债能力分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"流动资产",
                      "val":0
                    },
                    "b":{
                      "name":"流动负债",
                      "val":0
                    },
                    "c":{
                      "name":"存货",
                      "val":0
                    },
                    "d":{
                      "name":"货币资金",
                      "val":0
                    },
                    "e":{
                      "name":"短期投资",
                      "val":0
                    },
                    "f":{
                      "name":"应收票据",
                      "val":0
                    },
                    "g":{
                      "name":"应收帐款",
                      "val":0
                    },
                    "h":{
                      "name":"销售收入",
                      "val":0
                    },
                    "i":{
                      "name":"平均应收账",
                      "val":0
                    }
                  },
                  itemData:[
                    {
                      "j":1,
                      "k":63,
                      "l":321,
                      "m":23,
                      "n":673,
                      "o":843,
                      "p":323
                    },
                    {
                      "j":61,
                      "k":263,
                      "l":721,
                      "m":93,
                      "n":-3,
                      "o":233,
                      "p":-323
                    }
                  ],
                  itemGS:{
                    "j":{
                      "name":"流动比率",
                      "jisuan":"流动资产／流动负债",
                      "js":'this.itemTitle.a.val/this.itemTitle.b.val'
                    },
                    "k":{
                      "name":"速动比率",
                      "jisuan":"（流动资产－存货）／流动负债",
                      "js":"(this.itemTitle.a.val-this.itemTitle.c.val)/this.itemTitle.b.val"
                    },
                    "l":{
                      "name":"保守速动比率（超速动比率）",
                      "jisuan":"货币资金+短期投资+应收票据+应收帐款）／流动负债",
                      "js":"(this.itemTitle.d.val+this.itemTitle.e.val+this.itemTitle.f.val+this.itemTitle.g.val)/this.itemTitle.b.val"
                    },
                    "m":{
                      "name":"现金比率",
                      "jisuan":"（货币资金／流动负债）",
                      "js":"this.itemTitle.d.val/this.itemTitle.b.val"
                    },
                    "n":{
                      "name":"应收帐款周转率",
                      "jisuan":"销售收入／平均应收帐款",
                      "js":"this.itemTitle.h.val/this.itemTitle.i.val"
                    },
                    "o":{
                      "name":"应收帐款周转天数",
                      "jisuan":"360天／(销售收入／平均应收帐款)",
                      "js":"360/(this.itemTitle.h.val/this.itemTitle.i.val)"
                    },
                  }
                },
                {
                  title:"资本结构分析（或长期偿债能力分析",
                  loading:false,
                  itemTitle:{
                    "a":{
                      "name":"股东权益总额",
                      "val":0
                    },
                    "b":{
                      "name":"资产总额",
                      "val":0
                    },
                    "c":{
                      "name":"负债总额",
                      "val":0
                    },
                    "d":{
                      "name":"负债合计",
                      "val":0
                    },
                    "e":{
                      "name":"股东权益期末数",
                      "val":0
                    },
                    "f":{
                      "name":"长期负债",
                      "val":0
                    },
                    "g":{
                      "name":"短期借款",
                      "val":0
                    },
                    "h":{
                      "name":"一年内到期的长期负债",
                      "val":0
                    },
                    "i":{
                      "name":"长期借款",
                      "val":0
                    },
                    "j":{
                      "name":"应付债券",
                      "val":0
                    },
                    "k":{
                      "name":"长期应付款",
                      "val":0
                    },
                    "l":{
                      "name":"股东权益期末数",
                      "val":0
                    }
                  },
                  itemData:[
                    {
                      "j":1,
                      "k":63,
                      "l":321,
                      "m":23,
                      "n":673
                    },
                    {
                      "j":61,
                      "k":263,
                      "l":721,
                      "m":93,
                      "n":-3
                    }
                  ],
                  itemGS:{
                    "j":{
                      "name":"股东权益比率",
                      "jisuan":"股东权益总额／资产总额×100%",
                      "js":'this.itemTitle.a.val/this.itemTitle.b.val'
                    },
                    "k":{
                      "name":"资产负债比率",
                      "jisuan":"负债总额／资产总额×100%",
                      "js":"this.itemTitle.c.val/this.itemTitle.b.val×100%"
                    },
                    "l":{
                      "name":"资本负债比率",
                      "jisuan":"负债合计／股东权益期末数×100%",
                      "js":"(this.itemTitle.d.val+this.itemTitle.e.val+this.itemTitle.f.val+this.itemTitle.g.val)/this.itemTitle.b.val"
                    },
                    "m":{
                      "name":"长期负载比率",
                      "jisuan":"长期负债／资产总额×100%",
                      "js":"this.itemTitle.d.val/this.itemTitle.b.val"
                    },
                    "n":{
                      "name":"有息负债比率",
                      "jisuan":"（短期借款＋一年内到期的长期负债＋长期借款＋应付债券＋长期应付款）／股东权益期末数×100%",
                      "js":"this.itemTitle.h.val/this.itemTitle.i.val"
                    }
                  }
                },
              ]
            }
        },
        methods:{
        }
    }
</script>

<style scoped>

</style>
